# Generated by Django 5.2.4 on 2025-08-24 14:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMateriel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie de Matériel',
                'verbose_name_plural': 'Catégories de Matériaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, null=True)),
                ('numero_identite', models.CharField(blank=True, help_text="Numéro de pièce d'identité (CNI, passeport, etc.)", max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo_identite', models.ImageField(blank=True, null=True, upload_to='photos_identite/')),
                ('matricule', models.CharField(editable=False, max_length=50, unique=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='EtapeStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Ordre d’apparition dans le cycle de construction')),
            ],
            options={
                'verbose_name': 'Étape standard',
                'verbose_name_plural': 'Étapes standards',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('est_moral', models.BooleanField(default=False)),
                ('entreprise', models.CharField(blank=True, max_length=150, verbose_name='Nom de l’entreprise')),
                ('ninea', models.CharField(blank=True, max_length=100, verbose_name='NINEA')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('numero_identite', models.CharField(blank=True, max_length=100, unique=True, verbose_name='N° Pièce d’identité')),
                ('sexe', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10, verbose_name='Sexe')),
                ('photo_identite', models.ImageField(blank=True, null=True, upload_to='fournisseurs/photos')),
                ('telephone', models.CharField(blank=True, max_length=100, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('En pause', 'En pause'), ('Terminé', 'Terminé')], max_length=100, verbose_name='Statut')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('superficie', models.PositiveIntegerField(blank=True, null=True, verbose_name='Superficie du terrain (m²)')),
                ('surface_batie', models.PositiveIntegerField(blank=True, null=True, verbose_name='Surface bâtie (m²)')),
                ('nombre_pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pièces')),
                ('nombre_etages', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'étages")),
                ('a_piscine', models.BooleanField(default=False, verbose_name='Piscine')),
                ('volume_piscine', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume de la piscine (m³)')),
                ('a_ascenseur', models.BooleanField(default=False, verbose_name='Ascenseur')),
                ('nombre_ascenseurs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre d’ascenseurs')),
                ('a_climatisation', models.BooleanField(default=False, verbose_name='Climatisation')),
                ('nombre_clims', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de climatiseurs')),
                ('a_panneaux_solaires', models.BooleanField(default=False, verbose_name='Panneaux solaires')),
                ('puissance_panneaux', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance panneaux (kWc)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_moral', models.BooleanField(default=False, verbose_name='Entreprise ?')),
                ('entreprise', models.CharField(blank=True, max_length=100, null=True)),
                ('ninea', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_identite', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['entreprise', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Type de projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de projet',
                'verbose_name_plural': 'Types de projet',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('date_achat', models.DateField(verbose_name='Date d’achat')),
                ('mode_paiement', models.CharField(choices=[('espèces', 'Espèces'), ('virement', 'Virement'), ('chèque', 'Chèque'), ('autre', 'Autre')], max_length=50)),
                ('numero_facture', models.CharField(blank=True, max_length=100, verbose_name='N° Facture')),
                ('fichier_facture', models.FileField(blank=True, null=True, upload_to='achats/factures', verbose_name='Scan Facture')),
                ('tva_active', models.BooleanField(default=False, verbose_name='TVA active ?')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='core.fournisseur', verbose_name='Fournisseur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='core.projet')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('unite', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiaux', to='core.categoriemateriel')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('quantite', models.PositiveIntegerField(default=Decimal('0'), verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='Prix unitaire HT')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='Commentaire')),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.achat')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.materiel')),
            ],
            options={
                'verbose_name': 'Ligne d’achat',
                'verbose_name_plural': 'Lignes d’achat',
            },
        ),
        migrations.CreateModel(
            name='PhaseVersement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_totale', models.FloatField(blank=True, help_text='Superficie du terrain (en m²)', null=True)),
                ('surface_batie', models.FloatField(blank=True, help_text='Surface construite (en m²)', null=True)),
                ('nombre_etages', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_pieces', models.PositiveIntegerField(blank=True, null=True)),
                ('piscine', models.BooleanField(default=False)),
                ('ascenseur', models.BooleanField(default=False)),
                ('groupe_electrogene', models.BooleanField(default=False)),
                ('panneau_solaire', models.BooleanField(default=False)),
                ('parking_souterrain', models.BooleanField(default=False)),
                ('climatisation', models.BooleanField(default=False)),
                ('acces_handicapes', models.BooleanField(default=False)),
                ('performance_energetique', models.CharField(blank=True, help_text='Ex: A, B, C...', max_length=5, null=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristique', to='core.projet')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proprietaire', verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='projet',
            name='type_projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typeprojet', verbose_name='Type de projet'),
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_versement', models.DateField()),
                ('type_versement', models.CharField(choices=[('chèque', 'Chèque'), ('virement bancaire', 'Virement bancaire'), ('virement om', 'Virement Orange Money'), ('wave', 'Wave'), ('espèces', 'Espèces'), ('autres', 'Autres')], max_length=30)),
                ('fichier_justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs_versement/')),
                ('facture_pdf', models.FileField(blank=True, null=True, upload_to='factures_versement/')),
                ('libelle', models.CharField(blank=True, editable=False, max_length=100)),
                ('numero_facture', models.CharField(blank=True, editable=False, max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=60, null=True, verbose_name='Référence du paiement')),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements', to='core.etapestandard')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='core.phaseversement')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='core.projet')),
            ],
            options={
                'ordering': ['-date_versement'],
            },
        ),
        migrations.CreateModel(
            name='ProjetEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('date_affectation', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('contrat', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('observation', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.employe')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.projet')),
            ],
            options={
                'verbose_name': "Affectation d'employé",
                'verbose_name_plural': "Affectations d'employés",
                'unique_together': {('projet', 'employe')},
            },
        ),
    ]
