# Generated by Django 5.2.4 on 2025-08-26 05:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='cout_estime_lamane',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimation interne du coût de réalisation du projet.', max_digits=14, verbose_name='Coût estimé Lamane (XOF)'),
        ),
    ]
