# Generated by Django 5.2.4 on 2025-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projet_cout_estime_lamane'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapestandard',
            name='multi_niveau',
            field=models.BooleanField(default=False, help_text='Cochez si l’étape se décline par niveaux (R+0, R+1… ou S-1).'),
        ),
    ]
