# Generated by Django 5.2.4 on 2025-08-26 05:05

import django.db.models.constraints
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_etapestandard_multi_niveau'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phaseversement',
            options={'ordering': ['projet', 'ordre', 'id'], 'verbose_name': 'Phase de versement', 'verbose_name_plural': 'Phases de versement'},
        ),
        migrations.AddField(
            model_name='phaseversement',
            name='echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaseversement',
            name='etape_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phases_projets', to='core.etapestandard'),
        ),
        migrations.AddField(
            model_name='phaseversement',
            name='montant_prevu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='phaseversement',
            name='niveau',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaseversement',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='phaseversement',
            name='libelle',
            field=models.CharField(blank=True, help_text='Libellé libre (legacy). Sera auto-généré si étape/niveau fournis.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='phaseversement',
            index=models.Index(fields=['echeance'], name='core_phasev_echeanc_0b471a_idx'),
        ),
        migrations.AddIndex(
            model_name='phaseversement',
            index=models.Index(fields=['projet', 'ordre'], name='core_phasev_projet__085393_idx'),
        ),
        migrations.AddConstraint(
            model_name='phaseversement',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('projet', 'etape_standard', 'niveau'), name='uniq_projet_etape_niveau'),
        ),
    ]
