# Generated by Django 5.2.4 on 2025-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_phaseversement_options_phaseversement_echeance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapestandard',
            name='groupe',
            field=models.CharField(choices=[('gros', 'Gros œuvre'), ('second', 'Second œuvre')], db_index=True, default='gros', max_length=10),
        ),
    ]
