# Generated by Django 5.0.6 on 2026-03-16 12:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bonsortie_lignebon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancementchantier',
            name='effectif_encadrement',
            field=models.PositiveIntegerField(default=0, help_text='Chefs de chantier + conducteurs de travaux.', verbose_name='Effectif encadrement'),
        ),
        migrations.AlterField(
            model_name='avancementchantier',
            name='effectif_ouvriers',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'ouvriers présents sur le chantier ce mois.", verbose_name='Effectif ouvriers'),
        ),
        migrations.AlterField(
            model_name='avancementchantier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avancementchantier',
            name='incidents',
            field=models.TextField(blank=True, help_text='Mauvaises conditions météo, sinistres, non-conformités qualité.', verbose_name='Incidents / Non-conformités'),
        ),
        migrations.AlterField(
            model_name='avancementchantier',
            name='taux_financier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pourcentage du montant du marché déjà facturé/certifié.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avancement financier (%)'),
        ),
        migrations.AlterField(
            model_name='avancementchantier',
            name='taux_physique',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pourcentage des travaux physiquement réalisés.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avancement physique (%)'),
        ),
        migrations.AlterField(
            model_name='avancementchantier',
            name='taux_planifie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Avancement prévu selon le planning initial (courbe S).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avancement planifié (%)'),
        ),
        migrations.AlterField(
            model_name='bonsortie',
            name='reference',
            field=models.CharField(blank=True, help_text='Auto-générée à la sauvegarde (ex: BS-2025-001)', max_length=30, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='bonsortie',
            name='responsable',
            field=models.CharField(blank=True, help_text='Nom du chef de chantier ou conducteur de travaux', max_length=100, verbose_name='Responsable de la sortie'),
        ),
        migrations.AlterField(
            model_name='contratsoustraitance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignebonsortie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignebonsortie',
            name='quantite',
            field=models.DecimalField(decimal_places=2, help_text='Quantité sortie (en unité du matériau)', max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='marchetravaux',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text="Date de création de l'objet"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nombre_ascenseurs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'ascenseurs"),
        ),
        migrations.AlterField(
            model_name='situationmensuelle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='situationmensuelle',
            name='montant_a_payer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='= Montant net cumulé - Situations précédentes.', max_digits=16, verbose_name='Montant à payer cette situation (FCFA)'),
        ),
        migrations.AlterField(
            model_name='situationmensuelle',
            name='montant_brut_cumule',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Cumul des travaux réalisés depuis le début jusqu'à cette période.", max_digits=16, verbose_name='Montant brut cumulé HT (FCFA)'),
        ),
        migrations.AlterField(
            model_name='situationmensuelle',
            name='montant_net_cumule',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant brut cumulé moins retenue de garantie.', max_digits=16, verbose_name='Montant net cumulé HT (FCFA)'),
        ),
        migrations.AlterField(
            model_name='situationmensuelle',
            name='retenue_garantie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retenue de garantie prélevée sur cette situation (5% standard).', max_digits=14, verbose_name='Retenue de garantie (FCFA)'),
        ),
        migrations.AlterField(
            model_name='soustraitant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
