# Generated by Django 5.0.6 on 2026-03-25 15:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contrat_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='echeance_paiement',
            field=models.DateField(blank=True, help_text='Date limite de paiement au fournisseur.', null=True, verbose_name='Échéance de paiement'),
        ),
        migrations.AddField(
            model_name='achat',
            name='statut_paiement',
            field=models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('en_retard', 'En retard')], default='paye', max_length=20, verbose_name='Statut paiement fournisseur'),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Prix unitaire HT'),
        ),
    ]
