# Generated by Django 5.0.6 on 2026-03-25 22:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_achat_echeance_fournisseur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du compte')),
                ('type_compte', models.CharField(choices=[('banque', 'Compte bancaire'), ('caisse', 'Caisse'), ('mobile_money', 'Mobile Money (Wave/OM)')], max_length=15, verbose_name='Type')),
                ('banque', models.CharField(blank=True, max_length=100, verbose_name='Banque / Opérateur')),
                ('numero_compte', models.CharField(blank=True, max_length=50, verbose_name='N° de compte')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde initial')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Ex: 411000, 601000', max_length=10, unique=True, verbose_name='Code comptable')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_compte', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('charge', 'Charge'), ('produit', 'Produit')], max_length=10, verbose_name='Type')),
                ('classe', models.IntegerField(choices=[(1, '1 - Comptes de ressources durables'), (2, "2 - Comptes d'actif immobilisé"), (3, '3 - Comptes de stocks'), (4, '4 - Comptes de tiers'), (5, '5 - Comptes de trésorerie'), (6, '6 - Comptes de charges'), (7, '7 - Comptes de produits')], verbose_name='Classe SYSCOHADA')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='Prix unitaire HT'),
        ),
        migrations.CreateModel(
            name='BordereauPrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('date_edition', models.DateField(verbose_name="Date d'édition")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereaux', to='core.projet')),
            ],
            options={
                'verbose_name': 'Bordereau de prix',
                'verbose_name_plural': 'Bordereaux de prix',
                'ordering': ['-date_edition'],
                'unique_together': {('projet', 'numero', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DecompteGD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_travaux', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant des travaux')),
                ('montant_avenants', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant des avenants')),
                ('montant_penalites', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pénalités de retard')),
                ('montant_retenue_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Retenue de garantie')),
                ('montant_avances', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Avances versées')),
                ('montant_acomptes', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Acomptes payés')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('marche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dgd', to='core.marchetravaux')),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dgd', to='core.projet')),
            ],
            options={
                'verbose_name': 'Décompte Général Définitif',
                'verbose_name_plural': 'Décomptes Généraux Définitifs',
            },
        ),
        migrations.CreateModel(
            name='DocumentProjet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('pv_reunion', 'PV de réunion'), ('pv_reception', 'PV de réception'), ('plan', 'Plan / Dessin'), ('attachement', 'Attachement de travaux'), ('photo', 'Photo de chantier'), ('rapport', 'Rapport'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='documents_btp/', verbose_name='Fichier')),
                ('date_document', models.DateField(verbose_name='Date du document')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_btp', to='core.projet')),
            ],
            options={
                'verbose_name': 'Document BTP',
                'verbose_name_plural': 'Documents BTP',
                'ordering': ['-date_document'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_piece', models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° pièce')),
                ('date_ecriture', models.DateField(verbose_name='Date')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('journal', models.CharField(choices=[('AC', 'Journal des achats'), ('VT', 'Journal des ventes / versements'), ('BQ', 'Journal de banque'), ('CA', 'Journal de caisse'), ('OD', 'Opérations diverses')], max_length=2, verbose_name='Journal')),
                ('validee', models.BooleanField(default=False, verbose_name='Validée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='core.achat')),
                ('contrat_st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='core.contratsoustraitance')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='core.projet')),
                ('versement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='core.versement')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date_ecriture', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneBordereau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_prix', models.CharField(max_length=20, verbose_name='N° prix')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('unite', models.CharField(max_length=20, verbose_name='Unité')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire HT')),
                ('bordereau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.bordereauprix')),
            ],
            options={
                'verbose_name': 'Ligne de bordereau',
                'verbose_name_plural': 'Lignes de bordereau',
                'ordering': ['numero_prix'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=255, verbose_name='Libellé')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Crédit')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecriture', to='core.comptecomptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.ecriturecomptable')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'ordering': ['-debit', 'credit'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('direction', 'Direction générale'), ('comptable', 'Comptable'), ('chef_chantier', 'Chef de chantier'), ('gestionnaire', 'Gestionnaire de stock'), ('admin', 'Administrateur')], default='direction', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('projets_autorises', models.ManyToManyField(blank=True, related_name='utilisateurs_autorises', to='core.projet', verbose_name='Projets autorisés')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateur',
            },
        ),
        migrations.CreateModel(
            name='TransactionBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('virement_interne', 'Virement interne')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('date_transaction', models.DateField(verbose_name='Date')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_bancaires', to='core.achat')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.comptebancaire')),
                ('compte_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virements_recus', to='core.comptebancaire', verbose_name='Compte destination (virement interne)')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_bancaires', to='core.projet')),
                ('versement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_bancaires', to='core.versement')),
            ],
            options={
                'verbose_name': 'Transaction bancaire',
                'verbose_name_plural': 'Transactions bancaires',
                'ordering': ['-date_transaction', '-date_creation'],
            },
        ),
    ]
