# Generated by Django 5.0.6 on 2026-03-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comptebancaire_comptecomptable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='numero_identite',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='N° Pièce d’identité'),
        ),
    ]
