# Generated by Django 4.2.16 on 2026-04-06 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fournisseur_numero_identite_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVitrine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('hero_titre', models.CharField(default="Investissez dans l'immobilier au Senegal en toute securite", max_length=200, verbose_name='Titre principal (Hero)')),
                ('hero_sous_titre', models.TextField(default='LAMANE concoit, finance et realise des projets immobiliers fiables et structures.', verbose_name='Sous-titre Hero')),
                ('hero_bouton_texte', models.CharField(default='Decouvrir nos projets', max_length=60, verbose_name='Texte du bouton CTA')),
                ('hero_bouton_lien', models.CharField(default='#projets', max_length=200, verbose_name='Lien du bouton CTA')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='vitrine/hero/', verbose_name='Image Hero (fond)')),
                ('presentation_titre', models.CharField(default='Qui sommes-nous ?', max_length=150, verbose_name='Titre presentation')),
                ('presentation_texte', models.TextField(default="LAMANE est une societe de promotion immobiliere moderne basee au Senegal. Nous intervenons dans la conception, le montage, le financement et la realisation de projets immobiliers, principalement residentiels. Notre approche structuree et integree nous permet de maitriser l'ensemble de la chaine de valeur.", verbose_name='Texte de presentation')),
                ('stat_1_nombre', models.CharField(default='3+', max_length=20, verbose_name='Chiffre 1 (nombre)')),
                ('stat_1_label', models.CharField(default='Projets realises', max_length=60, verbose_name='Chiffre 1 (label)')),
                ('stat_2_nombre', models.CharField(default='10+', max_length=20, verbose_name='Chiffre 2 (nombre)')),
                ('stat_2_label', models.CharField(default="Annees d'experience", max_length=60, verbose_name='Chiffre 2 (label)')),
                ('stat_3_nombre', models.CharField(default='100%', max_length=20, verbose_name='Chiffre 3 (nombre)')),
                ('stat_3_label', models.CharField(default='Projets livres', max_length=60, verbose_name='Chiffre 3 (label)')),
                ('stat_4_nombre', models.CharField(default='50+', max_length=20, verbose_name='Chiffre 4 (nombre)')),
                ('stat_4_label', models.CharField(default='Clients satisfaits', max_length=60, verbose_name='Chiffre 4 (label)')),
                ('directeur_nom', models.CharField(default='Fondateur & Directeur General', max_length=100, verbose_name='Nom du directeur')),
                ('directeur_titre', models.CharField(default='Ingenieur Genie Civil - Geotechnique', max_length=100, verbose_name='Titre / poste')),
                ('directeur_message', models.TextField(default="LAMANE est nee d'une volonte de structurer le secteur immobilier et de creer des opportunites fiables pour la diaspora. Nous combinons expertise technique, innovation financiere et digitalisation pour transformer l'investissement immobilier au Senegal.", verbose_name='Mot du directeur')),
                ('directeur_photo', models.ImageField(blank=True, null=True, upload_to='vitrine/directeur/', verbose_name='Photo du directeur')),
                ('diaspora_titre', models.CharField(default="Investir depuis l'etranger", max_length=150, verbose_name='Titre section diaspora')),
                ('diaspora_texte', models.TextField(default="Vous vivez a l'etranger et souhaitez investir dans l'immobilier au Senegal ? LAMANE vous offre un modele securise : apport initial, structuration financiere, gestion centralisee et livraison dans les delais.", verbose_name='Description du modele diaspora')),
                ('diaspora_etape_1', models.CharField(default='Inscription & etude de votre projet', max_length=100)),
                ('diaspora_etape_2', models.CharField(default='Structuration du financement', max_length=100)),
                ('diaspora_etape_3', models.CharField(default='Lancement de la construction', max_length=100)),
                ('diaspora_etape_4', models.CharField(default='Suivi en temps reel', max_length=100)),
                ('diaspora_etape_5', models.CharField(default='Livraison cles en main', max_length=100)),
                ('contact_adresse', models.CharField(default='Dakar, Senegal', max_length=200, verbose_name='Adresse')),
                ('contact_telephone', models.CharField(default='+221 XX XXX XX XX', max_length=30, verbose_name='Telephone')),
                ('contact_email', models.EmailField(default='contact@lamane.sn', max_length=254, verbose_name='Email')),
                ('contact_whatsapp', models.CharField(blank=True, default='', max_length=30, verbose_name='WhatsApp')),
                ('meta_description', models.CharField(default='LAMANE - Societe de promotion immobiliere au Senegal. Construction, investissement diaspora, projets residentiels.', max_length=300, verbose_name='Meta description (SEO)')),
                ('footer_texte', models.CharField(default='LAMANE SARL - Promotion immobiliere & Gestion de projets BTP', max_length=200, verbose_name='Texte footer')),
            ],
            options={
                'verbose_name': 'Configuration du site vitrine',
                'verbose_name_plural': 'Configuration du site vitrine',
            },
        ),
        migrations.CreateModel(
            name='ProjetVitrine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du projet')),
                ('description', models.TextField(verbose_name='Description narrative')),
                ('localisation', models.CharField(max_length=100, verbose_name='Localisation')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('livre', 'Livre'), ('a_venir', 'A venir')], default='en_cours', max_length=30, verbose_name='Statut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vitrine/projets/', verbose_name='Image du projet')),
                ('points_forts', models.TextField(blank=True, help_text='Saisissez un point fort par ligne', verbose_name='Points forts (un par ligne)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Projet vitrine',
                'verbose_name_plural': 'Projets vitrine',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVitrine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('icone', models.CharField(default='fas fa-building', help_text='Ex: fas fa-building, fas fa-hard-hat, fas fa-chart-line', max_length=50, verbose_name='Classe icone FontAwesome')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre du service')),
                ('description', models.TextField(verbose_name='Description du service')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service vitrine',
                'verbose_name_plural': 'Services vitrine',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='TemoignageVitrine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('titre', models.CharField(blank=True, default='', max_length=100, verbose_name='Titre / profession')),
                ('texte', models.TextField(verbose_name='Temoignage')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vitrine/temoignages/', verbose_name='Photo')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Temoignage vitrine',
                'verbose_name_plural': 'Temoignages vitrine',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
