# Generated by Django 4.2.16 on 2026-04-06 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configvitrine_projetvitrine_servicevitrine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotMetre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du lot')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Code')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Lot de metre',
                'verbose_name_plural': 'Lots de metre',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PlanMetre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('nom', models.CharField(help_text='Ex: RDC, Etage 1, Toiture', max_length=150, verbose_name='Nom du plan')),
                ('fichier_pdf', models.FileField(upload_to='metres/plans/', verbose_name='Fichier PDF')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre (etage)')),
                ('echelle_pixels', models.FloatField(default=0, help_text='Nombre de pixels du segment de reference trace', verbose_name='Longueur de reference en pixels')),
                ('echelle_metres', models.FloatField(default=1.0, help_text='Longueur reelle correspondante en metres', verbose_name='Longueur de reference en metres')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_metre', to='core.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Plan de metre',
                'verbose_name_plural': 'Plans de metre',
                'ordering': ['projet', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('couleur', models.CharField(default='#FF0000', help_text='Code couleur hexadecimal, ex: #FF0000 pour rouge', max_length=7, verbose_name='Couleur (hex)')),
                ('unite', models.CharField(choices=[('ml', 'Metre lineaire (ml)'), ('m2', 'Metre carre (m2)'), ('m3', 'Metre cube (m3)'), ('u', 'Unite (U)'), ('ff', 'Forfait (FF)'), ('kg', 'Kilogramme (kg)')], default='ml', max_length=5, verbose_name='Unite')),
                ('outil', models.CharField(choices=[('ligne', 'Ligne (longueur)'), ('rectangle', 'Rectangle (surface)'), ('polygone', 'Polygone (surface)'), ('point', 'Point (comptage)')], default='ligne', max_length=15, verbose_name='Outil de trace')),
                ('epaisseur_defaut', models.DecimalField(decimal_places=3, default=0, help_text='Pour calcul de volume : surface x epaisseur', max_digits=6, verbose_name='Epaisseur par defaut (m)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire par defaut (FCFA)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_elements', to='core.lotmetre', verbose_name='Lot')),
            ],
            options={
                'verbose_name': "Type d'element",
                'verbose_name_plural': "Types d'elements",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TraceMetre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('coordonnees', models.JSONField(default=dict, verbose_name='Coordonnees du trace')),
                ('longueur_pixels', models.FloatField(default=0, verbose_name='Longueur en pixels')),
                ('surface_pixels', models.FloatField(default=0, verbose_name='Surface en pixels carres')),
                ('longueur_metres', models.FloatField(default=0, verbose_name='Longueur (m)')),
                ('surface_metres', models.FloatField(default=0, verbose_name='Surface (m2)')),
                ('volume_metres', models.FloatField(default=0, verbose_name='Volume (m3)')),
                ('quantite', models.FloatField(default=0, verbose_name='Quantite')),
                ('epaisseur', models.DecimalField(blank=True, decimal_places=3, help_text="Surcharge l'epaisseur du type d'element", max_digits=6, null=True, verbose_name='Epaisseur (m)')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, help_text="Surcharge le prix unitaire du type d'element", max_digits=12, null=True, verbose_name='Prix unitaire (FCFA)')),
                ('commentaire', models.CharField(blank=True, default='', max_length=200, verbose_name='Commentaire')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='core.planmetre', verbose_name='Plan')),
                ('type_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='core.typeelement', verbose_name="Type d'element")),
            ],
            options={
                'verbose_name': 'Trace de metre',
                'verbose_name_plural': 'Traces de metre',
                'ordering': ['plan', 'type_element__ordre', 'date_creation'],
            },
        ),
    ]
