# Generated by Django 4.2.16 on 2026-04-06 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lotmetre_planmetre_typeelement_tracemetre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmetre',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_metre', to='core.projet', verbose_name='Projet'),
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique global (UUID4)', primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de l’objet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('reference', models.CharField(blank=True, help_text='Generee automatiquement (DEV-2026-001)', max_length=30, unique=True, verbose_name='Reference')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du devis')),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_telephone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telephone')),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('localisation', models.CharField(blank=True, default='', max_length=200, verbose_name='Localisation du chantier')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoye'), ('valide', 'Valide'), ('refuse', 'Refuse')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('marge_pourcentage', models.DecimalField(decimal_places=2, default=15, help_text='Pourcentage de marge a appliquer sur le total metre', max_digits=5, verbose_name='Marge (%)')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('projet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_source', to='core.projet', verbose_name='Projet cree')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='planmetre',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_metre', to='core.devis', verbose_name='Devis'),
        ),
    ]
